name: wooberly_driver
description: A Wooberly Driver application.
version: 3.7.3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_crashlytics:
  firebase_messaging:
  shared_preferences: ^2.0.13
  provider: ^6.0.4
  graphql_flutter:
  permission_handler: ^10.2.0
  socket_io_client: ^1.0.2
  connectivity_plus:
  cached_network_image:
  flutter_svg:
  page_transition: ^2.0.5
  flutter_webview_pro: ^3.0.1+4
  flutter_widget_from_html_core: ^0.8.5+3
  google_maps_flutter:
    git:
      url: http://github.com/lukaskurz/plugins
      path: packages/google_maps_flutter/google_maps_flutter
      ref: main
  flutter_polyline_points: ^1.0.0
  package_info_plus: ^1.4.2
  flutter_local_notifications: ^9.4.0
  lottie: ^1.0.1
  video_player: ^2.4.0
  json_annotation: ^4.8.0
  cached_video_player: ^2.0.4
  geocoding:
    path: ./geocoding_2.0.1_changed/
  url_launcher: ^6.0.20
  app_settings: ^4.1.5
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  audioplayers:
  google_api_headers:
  gen_lang:
    path: ./gen_lang_0.1.3_changed/
  flutter_swipe_button: ^1.1.0
  slide_to_confirm: ^1.1.0
  just_the_tooltip: ^0.0.12
  camera_android:
    path: ./camera_android-0.10.2+1_changed/
  camera_avfoundation: ^0.9.7+1
  camera_platform_interface: ^2.2.0
  file_picker:
  file: ^6.1.4
  flutter_widget_offset: ^1.1.0
  otp_autofill: ^2.1.0
  sms_autofill: ^2.3.0
  pin_code_fields: ^7.4.0
  alt_sms_autofill: ^1.0.0
  soundpool: ^2.3.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - res/
    - res/drawable/
    - res/drawable/flags/
    - res/graphql/
    - assets/cities.json
    - assets/map_style.txt
    - assets/lottieloader.json
    - assets/ride_request.mp3
    - assets/video.mp4
    - assets/lottieloader_dark.json
    - assets/map_style_dark.txt
    - assets/ride_request.mp3
    - assets/correct.mp3
    - assets/wrong.mp3

  fonts:
    - family: HindVadodara
      fonts:
        - asset: font/HindVadodara-Regular.ttf
          weight: 400
        - asset: font/HindVadodara-Medium.ttf
          weight: 500
        - asset: font/HindVadodara-SemiBold.ttf
          weight: 600


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
